# Unitary matrix
If we have a complex matrix denoted as $U$ and its **conjugate transpose**, denoted as $U^*$, is equal to its inverse, then we can conclude that $U$ qualifies as a unitary matrix. 

This implies that the product of the conjugate transpose $U^*$ and matrix $U$, as well as the product of matrix $U$ and its conjugate transpose $U^*$, both equal the identity matrix $I$.

$$U^*U = UU^* = I$$

---
## Hadamard Gate

$$
\text{H}=
\frac{1}{\sqrt{2}}
\begin{bmatrix}
1 & 1\\
1 & -1
\end{bmatrix}
$$

In [1]:
import numpy as np

# Define the Hadamard gate matrix
Hadamard = 1/np.sqrt(2) * np.array([[1, 1],
                                    [1, -1]])

In [6]:
print(Hadamard.T @ Hadamard)

[[1. 0.]
 [0. 1.]]


In [5]:
Hadamard @ Hadamard.T

array([[1., 0.],
       [0., 1.]])

## The determinant of the Unitary matrix

From $$U^*U = UU^* = I$$

Consider 

$$
\begin{align}
\det(U^*U) = \det(UU^*) &= det(I)\\
\det(U^*)\det(U) = \det(U)\det(U^*) &= det(I)\\
\det(U^*)\det(U) = \det(U)\det(U^*) &= 1\\
\end{align}
$$

We know $\det(U^*) = \det(U)$. So,

$$
\begin{align}
\vert \det(U)\vert^2 &= 1\\
\vert \det(U)\vert &= 1
\end{align}$$

In [9]:
np.round(np.abs(np.linalg.det(Hadamard)))

1.0

## Eigenvalues of the Unitary matrix

$$U\bar v = \lambda\bar v$$

where $\lambda$ is an eigenvalue and $\bar v$ is an eigenvector

Take the conjugate transpose of both sides of this equation:

$$\begin{align}
U\bar v &= \lambda\bar v\\
(U\bar v)^*(U\bar v) &= (\lambda\bar v)^*(\lambda\bar v)\\
\bar v^* U^* U\bar v&= \lambda^2 \bar v^*\bar v\\
\end{align}$$

By $U^*U = I$ then
$$\begin{align}
\bar v^* \bar v&= \lambda^2 \bar v^*\bar v\\
0 &= (1-\lambda^2) v^* \bar v\\
|\lambda| &= 1
\end{align}$$

In [10]:
np.linalg.eigvals(Hadamard)

array([ 1., -1.])

## Inner product

Let $\langle\cdot\vert\cdot\rangle$ be the inner product. Let $u, v$ are vectors.

Consider 
$$
\begin{align}
\langle Uu\vert Uv\rangle &= (Uu)^\top (Uv)\\
\langle Uu\vert Uv\rangle &= (u^\top U^*) (Uv)\\
\langle Uu\vert Uv\rangle &= u^\top U^*Uv\\
\end{align}
$$

By $U^*U = I$ then

$$
\begin{align}
\langle Uu\vert Uv\rangle &= u^\top v\\
\langle Uu\vert Uv\rangle &= \langle u\vert v\rangle\\
\end{align}
$$

That means the $U$ transform cannot change the inner product of $u$ and $v$.

In [12]:
# create the samples vector u and v
u = np.array([[1],
              [0]])

v = np.array([[0],
              [1]])

# find the inner product value
np.dot(u.T, v)

array([[0]])

In [15]:
# Apply the unitary matrix
Uu = Hadamard @ u
Uv = Hadamard @ v

# find the inner product value
np.dot(Uu.T, Uv)

array([[0.]])