## [Linear Iterative Systems](https://www-users.cse.umn.edu/~olver/num_/lni.pdf)

*Definition 1:* A linear iterative system takes the from

$$u^{(k+1)} = Tu^{(k)}$$

where $u^{(0)} = a$, the coefficient matrix $T\in\mathbb{R}^{n\times n}$, and iterates are column vectors $u^{(k)}\in\mathbb{R}^n$

In [1]:
import numpy as np

In [2]:
# create the coefficient matrix T
n = 3
T = np.random.rand(n, n)

# Creta initial iterate u_0
u_0 = np.random.rand(n, 1)

In [3]:
u_1 = T @ u_0
u_1

array([[1.02660157],
       [0.46008334],
       [0.75031572]])

Consider 

$$
\begin{align}
u^{(1)} &= Tu^{(0)} = Ta\\
u^{(2)} &= Tu^{(1)} = T^2a\\
u^{(3)} &= Tu^{(2)} = T^3a\\
\end{align}
$$

So, in general 
$$u^{(k)} = T^k a$$

In [4]:
def u_k(k, a, T):
    return np.linalg.matrix_power(T, k) @ a

In [5]:
u_k(3, u_0, T)

array([[2.57063012],
       [1.69985621],
       [2.350547  ]])

Next, let's examine the eigenvalues $\lambda$ and corresponding eigenvectors $v$ of the matrix $T$:

$$Tv = \lambda v$$

Let $v = u^{(0)}$, and consider 
$$
\begin{align*}
T^kv &= T^{k-1}(Tv) \\
&= T^{k-1}(\lambda v)\\
&= T^{k-2}(\lambda Tv)\\
&= T^{k-2}(\lambda^2 v)\\
&\vdots\\
u^{(k)} &= \lambda^k v
\end{align*}
$$

By leveraging this, we can transform the solution into an exponential form: 
$$u^{(k)} = \lambda^k v$$

Consequently, it follows that, $$Tu^{(k)} = T(\lambda^k v) = \lambda^kTv$$

---

In [6]:
# create the coefficient matrix T
n = 5
T = np.array([[2, -3, 0],
              [2, -5, 0],
              [0, 0, 3]])

l, v = np.linalg.eig(T)

In [7]:
k = 3
lambda_value = l[0]
vect = v[:, 0]
u_k = lambda_value**k * vect

In [8]:
np.dot(T, u_k)

array([0.9486833 , 0.31622777, 0.        ])

In [9]:
(lambda_value ** k) * np.dot(T, vect)

array([0.9486833 , 0.31622777, 0.        ])

*Theorem 1:* If the coefficient matrix T is complete, then the general solution to the linear iterative system $u^{(k+1)} = Tu^{(k)}$ is given by

$$u^{(k)} = c_1\lambda_1^kv_1 + c_2\lambda_2^kv_2 + \cdots +c_n\lambda_n^kv_n$$

where $v_1, \ldots, v_n$ are the linearly independent eigenvectors and $\lambda_1, \ldots, \lambda_n$ the corresponding eigenvalues of $T$. The coefficient $c_1, \ldots, c_n$ are arbitrary scalars and are uniquely prescribed b the initial conditions $u^{(0)} = a$.

---

*Example:* The Fibonacci numbers are defined by the second order iterative scheme
$$u^{(k+2)} = u^{(k+1)} + u^{(k)}$$

with initial conditions $u^{(0)} = a,\ u^{(1)} = b$

we define the vector
$$\pmb{u}^{(k)} = 
\begin{bmatrix}
u^{(k))}\\
u^{(k+1))}
\end{bmatrix}
$$

So, the iterative systems is

$$
\begin{bmatrix}
u^{(k+1))}\\
u^{(k+2))}
\end{bmatrix} = 
\begin{bmatrix}
0 & 1\\
1 & 1
\end{bmatrix}
\begin{bmatrix}
u^{(k))}\\
u^{(k+1))}
\end{bmatrix}
$$

or 

$$\pmb{u}^{(k+1)} = T\pmb{u}^{(k)}$$

where $T = \begin{bmatrix}
0 & 1\\
1 & 1
\end{bmatrix}$.

In [20]:
from sympy import Matrix

In [13]:
T = Matrix([[0, 1],
            [1, 1]])

In [19]:
T.eigenvals()

{1/2 - sqrt(5)/2: 1, 1/2 + sqrt(5)/2: 1}

In [16]:
T.eigenvects()

[(1/2 - sqrt(5)/2,
  1,
  [Matrix([
   [-sqrt(5)/2 - 1/2],
   [               1]])]),
 (1/2 + sqrt(5)/2,
  1,
  [Matrix([
   [-1/2 + sqrt(5)/2],
   [               1]])])]

The eigenvalues of the $T$ matrix are
$$\begin{align}
\lambda_1 &= \frac{1+\sqrt{5}}{2}\\
\lambda_2 &= \frac{1-\sqrt{5}}{2}
\end{align}$$.

And, the eigenvalues of the $T$ matrix are
$$\begin{align}
v_1 &= \begin{bmatrix}\frac{-1+\sqrt{5}}{2} \\ 1\end{bmatrix}\\
v_2 &= \begin{bmatrix}\frac{-1-\sqrt{5}}{2} \\ 1\end{bmatrix}
\end{align}$$.

---
From the *theorem 1* we can write

$$\pmb{u}^{(k)} = 
\begin{bmatrix}
u^{(k))}\\
u^{(k+1))}
\end{bmatrix}
= c_1\lambda^k_1\begin{bmatrix}\frac{-1+\sqrt{5}}{2} \\ 1\end{bmatrix} 
+ c_2\lambda^k_2\begin{bmatrix}\frac{-1-\sqrt{5}}{2} \\ 1\end{bmatrix}$$

From the initial data

$$\pmb{u}^{(0)} 
= c_1\begin{bmatrix}\frac{-1+\sqrt{5}}{2} \\ 1\end{bmatrix} 
+ c_2\begin{bmatrix}\frac{-1-\sqrt{5}}{2} \\ 1\end{bmatrix}
=\begin{bmatrix}a\\ b \end{bmatrix}$$

So

$$c_1 = \frac{2a+(1+\sqrt{5})b}{2\sqrt{5}},\quad c_2 = \frac{2a+(1-\sqrt{5})b}{2\sqrt{5}}.$$

Finally

$$u^{(k)} = \frac{2a+(1+\sqrt{5})b}{2\sqrt{5}}\left(\frac{1+\sqrt{5}}{2}\right)^k + 
\frac{2a+(1-\sqrt{5})b}{2\sqrt{5}}\left(\frac{1-\sqrt{5}}{2}\right)^k.$$

Assume $a=0,\ b=1$, we got the *Binet formula*
$$u^{(k)} = \frac{1}{\sqrt{5}}\left[\left(\frac{1+\sqrt{5}}{2}\right)^k - \left(\frac{1-\sqrt{5}}{2}\right)^k\right]$$