In [1]:
import numpy as np

In [4]:
a00 = 1
a01 = 2
a02 = 3
a10 = 4
a11 = 5
a12 = 6
a20 = 7
a21 = 8
a22 = 9

A = np.array([[a00, a01, a02],
              [a10, a11, a12],
              [a20, a21, a22]])

print(A)
           
# np.array([[1,2,3],
#           [4,5,6],
#           [7,8,9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(A[0,0])
# 1

print(A[0:1, 2])
# np.array([[3], [6]]) 
      
print(A[2, 0:1])
# np.array([[7, 8]]) 

1
[3]
[7]


In [15]:
# Row Vector
row = np.array([[0,1,2]])

# Column Vector
column = np.array([[0],
                   [1],
                   [2]])

# Check Dimension of Array
print(row.shape)
# [1, 3]
print(column.shape)
# [3, 1]

(1, 3)
(3, 1)


In [17]:
np.dot(row, column)

array([[5]])

In [19]:
B = np.array([[1,1,1],
              [2,2,2],
              [3,3,3]])

C = np.array([[1,2,3],
              [1,2,3],
              [1,2,3]])

print(B.shape)
print(C.shape)

# Addition
print(B + C)

# subtraction
print(B - C)

# Dot
print(np.dot(B, C))

# Multiply Scalar
print(5 * B)

# Transpose
print(B.T)

(3, 3)
(3, 3)
[[2 3 4]
 [3 4 5]
 [4 5 6]]
[[ 0 -1 -2]
 [ 1  0 -1]
 [ 2  1  0]]
[[ 3  6  9]
 [ 6 12 18]
 [ 9 18 27]]
[[ 5  5  5]
 [10 10 10]
 [15 15 15]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [21]:
print(C.T)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [20]:
row = np.array([[0,1,2]])

# Column Vector
column = np.array([[0],
                   [1],
                   [2]])
print(row.shape) # (1, 3)
print(column.shape) # (3, 1)

# Dot
res1 = np.dot(row, column)
print(res1)
# [[5]]
print(res1.shape) # (1,1)

res2 = np.dot(column, row)
print(res2)
# [[0 0 0]
#  [0 1 2]
#  [0 2 4]]
print(res2.shape) # (3,3)

(1, 3)
(3, 1)
[[5]]
(1, 1)
[[0 0 0]
 [0 1 2]
 [0 2 4]]
(3, 3)
